spring.application.name=JobMS
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/job_db
spring.datasource.username=jeet
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=POSTGRESQL
